# 판다스(padas)

* 파이썬에서 데이터를 조작, 분석하기 위한 라이브러리
*   행과 열로 이루어진 테이블 형태의 데이터를 다룬다
*   matplotlib, seaborn 등 시각화 도구와 함께 사용

## 판다스 라이브러리 불러오기 
* 외부 패키지이므로 설치하여 사용하여야 
하지만 colab에는 기본적으로 설치가 되어있기 때문에 설치할 필요 없이 사용 가능
* pandas는 관용적으로 pd라는 별칭을 사용

In [ ]:
# pandas 라이브러리 불러오기
import pandas as pd

In [ ]:
pd.__version__

'1.3.5'

In [ ]:
# !pip install pandas --upgrade

## 시리즈(Series) 만들기
* pd.Series(1차원 리스트)
* pd.Series(딕셔너리)

### 즐겨먹는 야식 (단위 : %)
'치킨':77,'라면':37,'과자빵':33,'족발보쌈':32,'떡볶이순대':25,'피자':24

In [ ]:
# 즐겨먹는 야식 데이터로 시리즈 만들기
# 1차원 리스트로 만들기
s = pd.Series([77,37,33,32,25,24])
s

0    77
1    37
2    33
3    32
4    25
5    24
dtype: int64

In [ ]:
# 인덱스 이름 변경하기
s.index = ['치킨','라면','과자빵','족발보쌈','떡볶이순대','피자']
s

치킨       77
라면       37
과자빵      33
족발보쌈     32
떡볶이순대    25
피자       24
dtype: int64

In [ ]:
# 딕셔너리로 시리즈 생성하기
s = pd.Series({'치킨':77,'라면':37,'과자빵':33,'족발보쌈':32,'떡볶이순대':25,'피자':24})
s

치킨       77
라면       37
과자빵      33
족발보쌈     32
떡볶이순대    25
피자       24
dtype: int64

In [ ]:
# 자료 검색
s['라면']

37

In [ ]:
s[['라면','피자']]

라면    37
피자    24
dtype: int64

In [ ]:
s[:3]

치킨     77
라면     37
과자빵    33
dtype: int64

In [ ]:
# Series에 요소 추가
s['햄버거'] = 5
s

치킨       77
라면       37
과자빵      33
족발보쌈     32
떡볶이순대    25
피자       24
햄버거       5
dtype: int64

In [ ]:
# Series에 요소 삭제
del s['햄버거']
s

치킨       77
라면       37
과자빵      33
족발보쌈     32
떡볶이순대    25
피자       24
dtype: int64

## 데이터프레임 만들기
* 이중 리스트나 딕셔너리로 만들 수 있다.
* 파일을 읽어서 만들 수 있다.

### 나라별 혈액형 분포 데이터프레임 만들기
![나라별혈액형분포.png]()

#### 이중 리스트로 만들기

In [ ]:
df = pd.DataFrame([[32,31,28,10],
                   [27,32,29,13],
                   [38,22,30,10],
                   [42,10,44,4],
                   [43,11,41,5]],
                  index=['한국','중국','일본','미국','독일'],
                  columns=['A','B','O','AB']
                  )
df

     A   B   O  AB
한국  32  31  28  10
중국  27  32  29  13
일본  38  22  30  10
미국  42  10  44   4
독일  43  11  41   5

#### 딕셔너리로 만들기
* key가 컬럼명

In [ ]:
# 딕셔너리로 만들기
df = pd.DataFrame({'A':[32,27,38,42,43],
                   'B':[31,32,22,10,11],
                   'O':[28,29,30,44,41],
                   'AB':[10,13,10,4,5]},
                  index=['한국','중국','일본','미국','독일'])
df

     A   B   O  AB
한국  32  31  28  10
중국  27  32  29  13
일본  38  22  30  10
미국  42  10  44   4
독일  43  11  41   5

### 데이터프레임 정보, 통계량 보기
* df.info() 행과 열의 크기, 컬럼명, 값의 자료형 등 요약
* df.describe() 숫자형 변수에 대한 기초 통계량 출력
* df.shape 행과 열의 크기
* df.columns 컬럼명 확인
* df.index 인덱스명 확인

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 한국 to 독일
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   O       5 non-null      int64
 3   AB      5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes

In [ ]:
df.describe()

              A          B          O         AB
count   5.00000   5.000000   5.000000   5.000000
mean   36.40000  21.200000  34.400000   8.400000
std     6.80441  10.521407   7.503333   3.781534
min    27.00000  10.000000  28.000000   4.000000
25%    32.00000  11.000000  29.000000   5.000000
50%    38.00000  22.000000  30.000000  10.000000
75%    42.00000  31.000000  41.000000  10.000000
max    43.00000  32.000000  44.000000  13.000000

In [ ]:
df.shape

(5, 4)

In [ ]:
df.columns

Index(['A', 'B', 'O', 'AB'], dtype='object')

In [ ]:
df.index

Index(['한국', '중국', '일본', '미국', '독일'], dtype='object')

### 데이터프레임 컬럼명, 인덱스 지정

In [ ]:
# 컬럼명 변경, 지정하기
df.columns = ['A형', 'B형', 'O형', 'AB형']
df

    A형  B형  O형  AB형
한국  32  31  28   10
중국  27  32  29   13
일본  38  22  30   10
미국  42  10  44    4
독일  43  11  41    5

In [ ]:
# 행, 열 전환
df2 = df.T
df2

     한국  중국  일본  미국  독일
A형   32  27  38  42  43
B형   31  32  22  10  11
O형   28  29  30  44  41
AB형  10  13  10   4   5

In [ ]:
df

    A형  B형  O형  AB형
한국  32  31  28   10
중국  27  32  29   13
일본  38  22  30   10
미국  42  10  44    4
독일  43  11  41    5

### 데이터 추가, 삭제

In [ ]:
# 행 추가하기
df.loc['스위스'] = [50,7,40,3]
df

     A형  B형  O형  AB형
한국   32  31  28   10
중국   27  32  29   13
일본   38  22  30   10
미국   42  10  44    4
독일   43  11  41    5
스위스  50   7  40    3

In [ ]:
# 합계 행 추가하기
df.loc['합계'] = df.sum()

In [ ]:
# 합계 열 추가하기
df['합계'] = df.sum(axis=1)

In [ ]:
df

      A형   B형   O형  AB형   합계
한국    32   31   28   10  101
중국    27   32   29   13  101
일본    38   22   30   10  100
미국    42   10   44    4  100
독일    43   11   41    5  100
스위스   50    7   40    3  100
합계   232  113  212   45  602

In [ ]:
df.values

array([[ 32,  31,  28,  10, 101],
       [ 27,  32,  29,  13, 101],
       [ 38,  22,  30,  10, 100],
       [ 42,  10,  44,   4, 100],
       [ 43,  11,  41,   5, 100],
       [ 50,   7,  40,   3, 100],
       [232, 113, 212,  45, 602]])

### 데이터 행 삭제하기
* df.drop(index=[인덱스명], inplace=True)

In [ ]:
df.drop(index=['합계'])

     A형  B형  O형  AB형   합계
한국   32  31  28   10  101
중국   27  32  29   13  101
일본   38  22  30   10  100
미국   42  10  44    4  100
독일   43  11  41    5  100
스위스  50   7  40    3  100

In [ ]:
df

      A형   B형   O형  AB형   합계
한국    32   31   28   10  101
중국    27   32   29   13  101
일본    38   22   30   10  100
미국    42   10   44    4  100
독일    43   11   41    5  100
스위스   50    7   40    3  100
합계   232  113  212   45  602

In [ ]:
df.drop(index=['합계'], inplace=True)
df

     A형  B형  O형  AB형   합계
한국   32  31  28   10  101
중국   27  32  29   13  101
일본   38  22  30   10  100
미국   42  10  44    4  100
독일   43  11  41    5  100
스위스  50   7  40    3  100

### 데이터 열 삭제하기
* df.drop(columns=[컬럼명], inplace=True)

In [ ]:
df.drop(columns=['합계'], inplace=True)
df

     A형  B형  O형  AB형
한국   32  31  28   10
중국   27  32  29   13
일본   38  22  30   10
미국   42  10  44    4
독일   43  11  41    5
스위스  50   7  40    3

### 데이터 가져오기
* loc[인덱스, 컬럼명]
* iloc[행번호, 열번호]

In [ ]:
# 특정 행(나라) 가져오기
df.loc['한국']

A형     32
B형     31
O형     28
AB형    10
Name: 한국, dtype: int64

In [ ]:
# 특정 나라의 특정 혈액형 가져오기
df.loc['미국','O형']

44

In [ ]:
# 검색할 행이 여러개일 경우 리스트로 만들어서 조회한다
df.loc[['한국','일본']]

    A형  B형  O형  AB형
한국  32  31  28   10
일본  38  22  30   10

In [ ]:
# 특정 컬럼 가져오기
df['A형']

한국     32
중국     27
일본     38
미국     42
독일     43
스위스    50
Name: A형, dtype: int64

In [ ]:
df[['O형','B형']]

     O형  B형
한국   28  31
중국   29  32
일본   30  22
미국   44  10
독일   41  11
스위스  40   7

In [ ]:
# 슬라이싱으로 행 단위 데이터 가져오기
df[:3]

    A형  B형  O형  AB형
한국  32  31  28   10
중국  27  32  29   13
일본  38  22  30   10

In [ ]:
# 인덱스명으로 슬라이싱하여 행 단위 데이터 가져오기
df['한국':'미국']

    A형  B형  O형  AB형
한국  32  31  28   10
중국  27  32  29   13
일본  38  22  30   10
미국  42  10  44    4

In [ ]:
#혈액형별 평균값은?
df.mean()

A형     38.666667
B형     18.833333
O형     35.333333
AB형     7.500000
dtype: float64

In [ ]:
#혈액형별로 가장 많은 나라는?
df.idxmax()

A형     스위스
B형      중국
O형      미국
AB형     중국
dtype: object

In [ ]:
#혈액형별로 가장 적은 나라는?
df.idxmin()

A형      중국
B형     스위스
O형      한국
AB형    스위스
dtype: object

In [ ]:
# 나라별 가장 많은 혈액형은?
df.idxmax(axis=1)

한국     A형
중국     B형
일본     A형
미국     O형
독일     A형
스위스    A형
dtype: object

In [ ]:
# 나라별 가장 적은 혈액형은?
df.idxmin(axis=1)

한국     AB형
중국     AB형
일본     AB형
미국     AB형
독일     AB형
스위스    AB형
dtype: object

In [ ]:
df.iloc[1:4,0:3] #특정행, 열

    A형  B형  O형
중국  27  32  29
일본  38  22  30
미국  42  10  44

### 조건에 맞는 데이터 가져오기(불리언 인덱싱)
* df[조건]

In [ ]:
#특정 조건으로 행 검색하기
# A형이 40% 이상인 정보
df[df.A형 > 40]

     A형  B형  O형  AB형
미국   42  10  44    4
독일   43  11  41    5
스위스  50   7  40    3

In [ ]:
# A형이 40% 이상인 나라이름
df[df.A형 > 40].index

Index(['미국', '독일', '스위스'], dtype='object')

In [ ]:
# A형이 40% 이상인 나라의 B형 
df[df.A형 > 40].B형

미국     10
독일     11
스위스     7
Name: B형, dtype: int64

In [ ]:
# A형이 40% 이상이면서 O형이 30%이상인 나라
df[(df.A형 >= 40) & (df.O형 >= 30)]

     A형  B형  O형  AB형
미국   42  10  44    4
독일   43  11  41    5
스위스  50   7  40    3

In [ ]:
# B형이 A형보다 많은 나라
df[df.B형 >= df.A형]

    A형  B형  O형  AB형
중국  27  32  29   13

In [ ]:
# 데이터프레임을 csv 파일로 저장하기 
file = '혈액형.csv'
df.to_csv(file, encoding='cp949')

### csv 파일 불러와서 데이터프레임 만들기
* 데이터위치 (국가통계포털 - 인구총조사 - 인구밀도)
https://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1B08024&vw_cd=MT_ZTITLE&list_id=A1_13&scrId=&seqNo=&lang_mode=ko&obj_var_id=&itm_id=&conn_path=MT_ZTITLE&path=%252FstatisticsList%252FstatisticsListIndex.do

In [ ]:
import pandas as pd
df = pd.read_csv('인구밀도_인구주택총조사기준__20220831220343.csv', encoding='cp949')
df

      행정구역별     2019     2020     2021
0        전국    515.7    516.2    515.2
1     서울특별시  15926.9  15839.0  15650.1
2     부산광역시   4379.7   4348.9   4316.4
3     대구광역시   2750.3   2728.6   2702.2
4     인천광역시   2776.6   2765.1   2772.8
5     광주광역시   2972.7   2948.5   2944.0
6     대전광역시   2777.5   2758.1   2742.8
7     울산광역시   1076.9   1069.0   1055.0
8   세종특별자치시    727.3    761.3    787.7
9       경기도   1305.0   1325.3   1338.9
10      강원도     90.3     90.4     90.4
11     충청북도    220.0    220.3    219.4
12     충청남도    265.4    264.0    263.8
13     전라북도    224.0    223.4    221.4
14     전라남도    144.8    144.9    143.9
15     경상북도    140.2    138.9    138.4
16     경상남도    317.6    316.2    313.6
17      제주도    359.4    362.6    363.8

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   행정구역별   18 non-null     object
 1   2019    18 non-null     float64
 2   2020    18 non-null     float64
 3   2021    18 non-null     float64
dtypes: float64(3), object(1)
memory usage: 704.0+ bytes

In [ ]:
# 전국 데이터 삭제
df.drop(0,inplace=True)

In [ ]:
df

      행정구역별     2019     2020     2021
0        전국    515.7    516.2    515.2
1     서울특별시  15926.9  15839.0  15650.1
2     부산광역시   4379.7   4348.9   4316.4
3     대구광역시   2750.3   2728.6   2702.2
4     인천광역시   2776.6   2765.1   2772.8
5     광주광역시   2972.7   2948.5   2944.0
6     대전광역시   2777.5   2758.1   2742.8
7     울산광역시   1076.9   1069.0   1055.0
8   세종특별자치시    727.3    761.3    787.7
9       경기도   1305.0   1325.3   1338.9
10      강원도     90.3     90.4     90.4
11     충청북도    220.0    220.3    219.4
12     충청남도    265.4    264.0    263.8
13     전라북도    224.0    223.4    221.4
14     전라남도    144.8    144.9    143.9
15     경상북도    140.2    138.9    138.4
16     경상남도    317.6    316.2    313.6
17      제주도    359.4    362.6    363.8

In [ ]:
# 컬럼명 변경하기
df = df.rename(columns = {'행정구역별' : '행정구역'})

In [ ]:
df

       행정구역     2019     2020     2021
1     서울특별시  15926.9  15839.0  15650.1
2     부산광역시   4379.7   4348.9   4316.4
3     대구광역시   2750.3   2728.6   2702.2
4     인천광역시   2776.6   2765.1   2772.8
5     광주광역시   2972.7   2948.5   2944.0
6     대전광역시   2777.5   2758.1   2742.8
7     울산광역시   1076.9   1069.0   1055.0
8   세종특별자치시    727.3    761.3    787.7
9       경기도   1305.0   1325.3   1338.9
10      강원도     90.3     90.4     90.4
11     충청북도    220.0    220.3    219.4
12     충청남도    265.4    264.0    263.8
13     전라북도    224.0    223.4    221.4
14     전라남도    144.8    144.9    143.9
15     경상북도    140.2    138.9    138.4
16     경상남도    317.6    316.2    313.6
17      제주도    359.4    362.6    363.8

In [ ]:
# 행정구역별 평균을 구하여 평균 컬럼을 추가
df['평균'] = df.mean(axis=1, numeric_only=True)
#df['평균'] = df.mean(axis=1)
df

       행정구역     2019     2020     2021            평균
1     서울특별시  15926.9  15839.0  15650.1  15805.333333
2     부산광역시   4379.7   4348.9   4316.4   4348.333333
3     대구광역시   2750.3   2728.6   2702.2   2727.033333
4     인천광역시   2776.6   2765.1   2772.8   2771.500000
5     광주광역시   2972.7   2948.5   2944.0   2955.066667
6     대전광역시   2777.5   2758.1   2742.8   2759.466667
7     울산광역시   1076.9   1069.0   1055.0   1066.966667
8   세종특별자치시    727.3    761.3    787.7    758.766667
9       경기도   1305.0   1325.3   1338.9   1323.066667
10      강원도     90.3     90.4     90.4     90.366667
11     충청북도    220.0    220.3    219.4    219.900000
12     충청남도    265.4    264.0    263.8    264.400000
13     전라북도    224.0    223.4    221.4    222.933333
14     전라남도    144.8    144.9    143.9    144.533333
15     경상북도    140.2    138.9    138.4    139.166667
16     경상남도    317.6    316.2    313.6    315.800000
17      제주도    359.4    362.6    363.8    361.933333

In [ ]:
df.loc['18'] = ['평균', df['2019'].mean(), df['2020'].mean(),df['2021'].mean(), df['평균'].mean()]

In [ ]:
df.drop(index='18', inplace=True)
df

       행정구역     2019     2020     2021            평균
1     서울특별시  15926.9  15839.0  15650.1  15805.333333
2     부산광역시   4379.7   4348.9   4316.4   4348.333333
3     대구광역시   2750.3   2728.6   2702.2   2727.033333
4     인천광역시   2776.6   2765.1   2772.8   2771.500000
5     광주광역시   2972.7   2948.5   2944.0   2955.066667
6     대전광역시   2777.5   2758.1   2742.8   2759.466667
7     울산광역시   1076.9   1069.0   1055.0   1066.966667
8   세종특별자치시    727.3    761.3    787.7    758.766667
9       경기도   1305.0   1325.3   1338.9   1323.066667
10      강원도     90.3     90.4     90.4     90.366667
11     충청북도    220.0    220.3    219.4    219.900000
12     충청남도    265.4    264.0    263.8    264.400000
13     전라북도    224.0    223.4    221.4    222.933333
14     전라남도    144.8    144.9    143.9    144.533333
15     경상북도    140.2    138.9    138.4    139.166667
16     경상남도    317.6    316.2    313.6    315.800000
17      제주도    359.4    362.6    363.8    361.933333

In [ ]:
# 인구밀도가 평균이 1000이 넘는 행정구역 
df[df.평균 > 1000].행정구역

1    서울특별시
2    부산광역시
3    대구광역시
4    인천광역시
5    광주광역시
6    대전광역시
7    울산광역시
9      경기도
Name: 행정구역, dtype: object

In [ ]:
# 평균이 최소값을 가지는 행정구역
df[df.평균.min() == df.평균].행정구역

10    강원도
Name: 행정구역, dtype: object

In [ ]:
# 평균 컬럼값으로 정렬
df_sorted = df.sort_values(by='평균', ascending=False)
df_sorted

       행정구역     2019     2020     2021            평균
1     서울특별시  15926.9  15839.0  15650.1  15805.333333
2     부산광역시   4379.7   4348.9   4316.4   4348.333333
5     광주광역시   2972.7   2948.5   2944.0   2955.066667
4     인천광역시   2776.6   2765.1   2772.8   2771.500000
6     대전광역시   2777.5   2758.1   2742.8   2759.466667
3     대구광역시   2750.3   2728.6   2702.2   2727.033333
9       경기도   1305.0   1325.3   1338.9   1323.066667
7     울산광역시   1076.9   1069.0   1055.0   1066.966667
8   세종특별자치시    727.3    761.3    787.7    758.766667
17      제주도    359.4    362.6    363.8    361.933333
16     경상남도    317.6    316.2    313.6    315.800000
12     충청남도    265.4    264.0    263.8    264.400000
13     전라북도    224.0    223.4    221.4    222.933333
11     충청북도    220.0    220.3    219.4    219.900000
14     전라남도    144.8    144.9    143.9    144.533333
15     경상북도    140.2    138.9    138.4    139.166667
10      강원도     90.3     90.4     90.4     90.366667

In [ ]:
# 인덱스 재설정
df_sorted.reset_index()
#df_sorted.reset_index(drop=True, inplace=True)

    index     행정구역     2019     2020     2021            평균
0       1    서울특별시  15926.9  15839.0  15650.1  15805.333333
1       2    부산광역시   4379.7   4348.9   4316.4   4348.333333
2       5    광주광역시   2972.7   2948.5   2944.0   2955.066667
3       4    인천광역시   2776.6   2765.1   2772.8   2771.500000
4       6    대전광역시   2777.5   2758.1   2742.8   2759.466667
5       3    대구광역시   2750.3   2728.6   2702.2   2727.033333
6       9      경기도   1305.0   1325.3   1338.9   1323.066667
7       7    울산광역시   1076.9   1069.0   1055.0   1066.966667
8       8  세종특별자치시    727.3    761.3    787.7    758.766667
9      17      제주도    359.4    362.6    363.8    361.933333
10     16     경상남도    317.6    316.2    313.6    315.800000
11     12     충청남도    265.4    264.0    263.8    264.400000
12     13     전라북도    224.0    223.4    221.4    222.933333
13     11     충청북도    220.0    220.3    219.4    219.900000
14     14     전라남도    144.8    144.9    143.9    144.533333
15     15     경상북도    140.2    138.9    138.4    139.166667
16     10      강원도     90.3     90.4     90.4     90.366667

In [ ]:
df_sorted.index =df_sorted.index + 1
df_sorted

       행정구역     2019     2020     2021            평균
2     서울특별시  15926.9  15839.0  15650.1  15805.333333
3     부산광역시   4379.7   4348.9   4316.4   4348.333333
4     광주광역시   2972.7   2948.5   2944.0   2955.066667
5     인천광역시   2776.6   2765.1   2772.8   2771.500000
6     대전광역시   2777.5   2758.1   2742.8   2759.466667
7     대구광역시   2750.3   2728.6   2702.2   2727.033333
8       경기도   1305.0   1325.3   1338.9   1323.066667
9     울산광역시   1076.9   1069.0   1055.0   1066.966667
10  세종특별자치시    727.3    761.3    787.7    758.766667
11       전국    515.7    516.2    515.2    515.700000
12      제주도    359.4    362.6    363.8    361.933333
13     경상남도    317.6    316.2    313.6    315.800000
14     충청남도    265.4    264.0    263.8    264.400000
15     전라북도    224.0    223.4    221.4    222.933333
16     충청북도    220.0    220.3    219.4    219.900000
17     전라남도    144.8    144.9    143.9    144.533333
18     경상북도    140.2    138.9    138.4    139.166667
19      강원도     90.3     90.4     90.4     90.366667

In [ ]:
df

       행정구역     2019     2020     2021            평균
0        전국    515.7    516.2    515.2    515.700000
1     서울특별시  15926.9  15839.0  15650.1  15805.333333
2     부산광역시   4379.7   4348.9   4316.4   4348.333333
3     대구광역시   2750.3   2728.6   2702.2   2727.033333
4     인천광역시   2776.6   2765.1   2772.8   2771.500000
5     광주광역시   2972.7   2948.5   2944.0   2955.066667
6     대전광역시   2777.5   2758.1   2742.8   2759.466667
7     울산광역시   1076.9   1069.0   1055.0   1066.966667
8   세종특별자치시    727.3    761.3    787.7    758.766667
9       경기도   1305.0   1325.3   1338.9   1323.066667
10      강원도     90.3     90.4     90.4     90.366667
11     충청북도    220.0    220.3    219.4    219.900000
12     충청남도    265.4    264.0    263.8    264.400000
13     전라북도    224.0    223.4    221.4    222.933333
14     전라남도    144.8    144.9    143.9    144.533333
15     경상북도    140.2    138.9    138.4    139.166667
16     경상남도    317.6    316.2    313.6    315.800000
17      제주도    359.4    362.6    363.8    361.933333

In [ ]:
# 인구밀도가 늘어나고 있는 도시
df[df['2021'] > df.평균 ].행정구역

4       인천광역시
8     세종특별자치시
9         경기도
10        강원도
17        제주도
Name: 행정구역, dtype: object

### 데이터프레임을 파일로 저장하기

In [ ]:
file = '인구밀도2.csv'
df.to_csv(file, index=False)